# Generated by Django 5.1.7 on 2025-03-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_submission_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='cumulative_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
