# Generated by Django 5.1.7 on 2025-03-15 17:25

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_userstats_cumulative_stats_delete_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='cumulative_stats',
            field=models.JSONField(default=tracker.models.default_cumulative_stats),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='heatmap_data',
            field=models.JSONField(default=tracker.models.default_heatmap_data),
        ),
    ]
