# Generated by Django 5.1.7 on 2025-03-24 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_userstats_cumulative_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_stats', to='tracker.userprofile'),
        ),
        migrations.CreateModel(
            name='GitHubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('total_contributions', models.IntegerField(default=0)),
                ('contribution_heatmap', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_stats', to='tracker.userprofile')),
            ],
        ),
    ]
